import Color from 'color';

export const colors = {
  blue: Color('#0085FF'),
  onBlue: Color('white'),
  teal: Color('#14b8a6'),
  onTeal: Color('white'),
  red: Color('#EE5555'),
  onRed: Color('white'),
  green: Color('#45DC81'),
  onGreen: Color('white'),
  white: Color('#FFFFFF'),
  onWhite: Color('black'),
  grey: Color('#FAFAFA'),
  onGrey: Color('black'),
  mdGrey: Color('#ffffff'),
  onMdGrey: Color('black'),
  black: Color('#000000'),
  onBlack: Color('white'),
  ltBlack: Color('#1d1d1d'),
  onLtBlack: Color('white'),
  mdBlack: Color('#1e1e1e'),
  onMdBlack: Color('white'),
  hvBlack: Color('#151515'),
  onHvBlack: Color('white'),
  greyHv: Color('#6b7280'),
  onGreyHv: Color('white'),
  amber: Color('#f59e0b'),
  onAmber: Color('white'),
  lime: Color('#84cc16'),
  onLime: Color('white'),
  emerald: Color('#10b981'),
  onEmerald: Color('white'),
  indigo: Color('#6366f1'),
  onIndigo: Color('white'),
  purple: Color('#a855f7'),
  onPurple: Color('white'),
  rose: Color('#f43f5e'),
  onRose: Color('white'),
  sky: Color('#0ea5e9'),
  onSky: Color('white'),
};
